# Generated by Django 2.0.4 on 2018-04-10 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('idAposta', models.AutoField(primary_key=True, serialize=False)),
                ('placarPais1', models.PositiveIntegerField()),
                ('placarPais2', models.PositiveIntegerField()),
                ('statusAposta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('idJogador', models.AutoField(primary_key=True, serialize=False)),
                ('nomeJogador', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('creditos', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('NomePais', models.CharField(max_length=32)),
                ('siglaPais', models.CharField(max_length=3)),
                ('arquivoDeImagem', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('idPartida', models.AutoField(primary_key=True, serialize=False)),
                ('placarPais1', models.PositiveIntegerField(default=0)),
                ('placarPais2', models.PositiveIntegerField(default=0)),
                ('resultado', models.IntegerField()),
                ('datainicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataFim', models.DateTimeField(default=django.utils.timezone.now)),
                ('idPais1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_1', to='Bolao.Pais')),
                ('idPais2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_2', to='Bolao.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='aposta',
            name='idJogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bolao.Jogador'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='idPartida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bolao.Partida'),
        ),
    ]
