# Generated by Django 2.0.4 on 2018-04-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bolao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('idEstadio', models.AutoField(primary_key=True, serialize=False)),
                ('nomeEstadio', models.CharField(max_length=25)),
                ('estadoEstadio', models.CharField(max_length=25)),
                ('siglaEstado', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='idEstadio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Bolao.Estadio'),
            preserve_default=False,
        ),
    ]
