# Generated by Django 2.0.4 on 2018-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bolao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='tituloPartida',
            field=models.CharField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
