# Generated by Django 2.0.4 on 2018-04-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bolao', '0002_partida_titulopartida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='tituloPartida',
        ),
    ]
